<form class="form-search" action="" method="get">
    <div class="input-append">
        <input type="text" name="sku" class="input-large search-query" placeholder="Filter Products by SKU" value="<?=$this->escapeHTML($sku)?>">
        <button type="submit" class="btn">Search</button>
    </div>
</form>


<?php
foreach($results as $product) {
    $url = $this->url('productmanage', array(
        'id'=>$product['id']
    ));
    echo '<ul class="well well-small sku-product-result" onclick="window.location=\'' . $url . '\'">';
        echo '<li>ID: ' . $this->escapeHTML($product['id']) . '</li>';
        echo '<li>SKU: ' . $this->escapeHTML($product['sku'] ? $product['sku'] : 'N/A') . '</li>';
    echo '</ul>';
}