<form action="?" method="get">
    <table class="table table-bordered table-striped">
        <tr>
        <?php
        foreach($schema->getLevels() as $level) {
            echo '<th>'.$this->escapeHTML($level).'</th>';
        }
        ?>
        </tr>

        <tr>
        <?php
        foreach($schema->getLevels() as $level) {
            echo '<th><input type="text" name="'.$this->escapeHTMLAttr($level).'" value="'.$this->escapeHTMLAttr(isset($_GET[$level]) ? $_GET[$level] : '').'" />';
            echo '<input type="submit" value="Filter" /></th>';
        }
        ?>
        </tr>

        <?php
        foreach($vehicles as $vehicle) {
            ?>
            <tr>
                <?php
                foreach($vehicle->toTitleArray() as $title) {
                    echo '<td>'.$title.'</td>';
                }
                ?>
            </tr>
            <?php
        }
        ?>
    </table>
</form>