<form action="?" method="get">
    <table class="table table-bordered table-striped">
        <tr>
        <?php
        foreach($schema->getLevels() as $level) {
            echo '<th>'.$this->escapeHTML($level).'</th>';
        }
        ?>
        </tr>

        <tr>
        <?php
        foreach($schema->getLevels() as $level) {
            echo '<th>';
            echo '<input type="text" name="'.$this->escapeHTMLAttr($level).'" value="'.$this->escapeHTMLAttr(isset($_GET[$level]) ? $_GET[$level] : '').'" />';
            echo '<input type="submit" value="Filter" />';
            echo '</th>';
        }
        ?>
        </tr>

        <?php
        foreach($vehicles as $vehicle) {
            ?>
            <tr>
                <?php
                foreach($vehicle->toTitleArray() as $level=>$title) {
                    echo '<td><a href="?'.$level.'='.$this->escapeHTMLAttr($title).'">'.$this->escapeHTML($title).'</a></td>';
                }
                ?>
            </tr>
            <?php
        }
        ?>
    </table>
</form>