<?php
if(!isset($route)) {
    $route = null;
}
if(!isset($module)) {
    $module = null;
}
echo $this->doctype();
?>

<html lang="en">
<head>
    <?=$this->partial('layout/head.phtml')?>
</head>
<body>
<?=$this->partial('layout/navbar.phtml')?>

<div class="container">

    <?=$this->partial('layout/messages.phtml')?>
    <?php echo $this->content; ?>
    <?=$this->partial('layout/footer.phtml')?>
</div>

<?php echo $this->inlineScript() ?>
</body>
</html>
