<?php
if(!isset($route)) {
    $route = null;
}
if(!isset($module)) {
    $module = null;
}
echo $this->doctype();
?>

<html lang="en">
    <head>
        <?=$this->partial('layout/head.phtml')?>
    </head>
    <body>
        <?=$this->partial('layout/navbar.phtml', array(
            'route' => $route,
            'module' => $module,
        ))?>

        <div class="container">

            <?=$this->partial('layout/messages.phtml')?>
            <div class="row">
                <div class="span2">
                    <?=$this->partial('layout/sidebar.phtml', array(
                        'route' => $route,
                        'module' => $module,
                    ))?>
                </div>
                <div class="span10">
                    <?php echo $this->content; ?>
                </div>
            </div>

            <?=$this->partial('layout/footer.phtml')?>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
