<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li><a href="<?php echo $this->url('dashboard') ?>"><?php echo $this->translate('Dashboard') ?></a></li>
                            <li><a href="<?php echo $this->url('vehicles') ?>"><?php echo $this->translate('Vehicles') ?></a></li>
                            <li><a href="<?php echo $this->url('product-fitments') ?>"><?php echo $this->translate('Product Fitments') ?></a></li>
                            <li><a href="<?php echo $this->url('settings') ?>"><?php echo $this->translate('Settings') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?=$this->partial('layout/messages.phtml')?>
            <div class="row">
                <div class="span2">
                    <?php
                    switch($module) {
                        case 'Fitments':
                            echo $this->partial('layout/menu/fitments.phtml');
                        break;
                        case 'Vehicles':
                            echo $this->partial('layout/menu/vehicles.phtml');
                        break;
                        case 'Settings':
                            echo $this->partial('layout/menu/settings.phtml');
                        break;
                    }
                    ?>
                </div>
                <div class="span10">
                    <?php echo $this->content; ?>
                </div>
            </div>

            <hr>
            <footer>
                <p>&copy; 2013 VehicleFits</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
