<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

            <img src="<?php echo $this->basePath()?>/img/small_logo.png" class="brand" />
            <ul class="nav">
                <li <?=$route == 'dashboard' ? 'class="active"' : ''?>><a href="<?php echo $this->url('dashboard') ?>"><?php echo $this->translate('Dashboard') ?></a></li>
                <li <?=$module == 'Vehicles' ? 'class="active"' : ''?>><a href="<?php echo $this->url('vehicles') ?>"><?php echo $this->translate('Vehicles') ?></a></li>
                <li <?=$module == 'Fitments' ? 'class="active"' : ''?>><a href="<?php echo $this->url('fitments') ?>"><?php echo $this->translate('Product Fitments') ?></a></li>
                <li <?=$module == 'Settings' ? 'class="active"' : ''?>><a href="<?php echo $this->url('settings') ?>"><?php echo $this->translate('Settings') ?></a></li>
            </ul>

            <ul class="nav pull-right">
                <li><a href="<?php echo $this->url('logout') ?>">Log Out</a></li>
            </ul>
        </div>

    </div>
</div>