<ul class="nav nav-pills nav-stacked">
    <li <?=$route == 'vehicles' ? 'class="active"' : ''?>><a href="<?=$this->url('vehicles')?>">Manage</a></li>
    <li <?=$route == 'vehicles-import' ? 'class="active"' : ''?>><a href="<?=$this->url('vehicles-import')?>">Import</a></li>
    <li <?=$route == 'vehicles-export' ? 'class="active"' : ''?>><a href="<?=$this->url('vehicles-export')?>">Export</a></li>
</ul>